### ISSUE TITLE
HTTP header "X_FORWARDED_EMAIL" not set and request URI not whitelisted.

### ISSUE THREAD

**Issue by rabbl** [mara/mara-example-project#9]
We have setup mara [#6d6d857](https://github.com/mara/mara-example-project/commit/6d6d857374f7950a7d564250b38852c2ca1ac607) in a docker-container and it works like a charm.

Merging the newest [upstream-version](https://github.com/mara/mara-example-project/commit/9f1d2a57f09fcb9bfe28366f017cddadb8f0f46c) shows a 400 error with the message:

```
HTTP header "X_FORWARDED_EMAIL" not set and request URI not whitelisted.
```

Any idea how to fix this bug or where to start debugging?

**Comment by rabbl** [comment]
Found it, happens if you're using the old local_setup.py with the new version.
The new one has more options and does some monkey-patching.

I'll close this issue so.

**Comment by martin-loetzsch** [comment]
Glad you found it & sorry for the late response
